image: mcr.microsoft.com/dotnet/sdk:8.0
variables:
  STACK_NAME: robot-app


stages:
  - test
  - build
  - deploy

test:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - 'dotnet restore'
    - 'dotnet test --no-restore'
  artifacts:
    paths:
      - ./*

create_docker_image:
  stage: build
  variables:
    GIT_STRATEGY: none
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg DATABASE_CA_CERTIFICATE=${DATABASE_CA_CERTIFICATE} -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  needs: [ "test" ]
  dependencies:
    - test
  only:
    - main

package_libraries:
  stage: build
  script:
    - 'echo "Packaging libraries..."'
    - 'dotnet pack RobotAppLibrary.Exposition/RobotAppLibrary.Exposition.csproj -c Release /p:PackageVersion=$CI_COMMIT_TAG -o ./packages'
    - 'dotnet pack RobotAppLibrary.Indicators/RobotAppLibrary.Indicators.csproj -c Release /p:PackageVersion=$CI_COMMIT_TAG -o ./packages'
    - 'dotnet pack RobotAppLibrary.Modeles/RobotAppLibrary.Modeles.csproj -c Release /p:PackageVersion=$CI_COMMIT_TAG -o ./packages'
    - 'echo "Publishing packages to NuGet.org..."'
    - 'for pkg in ./packages/*.nupkg; do dotnet nuget push "$pkg" --source "https://api.nuget.org/v3/index.json" --api-key $NUGET_API_KEY; done'
  artifacts:
    paths:
      - ./packages/*.nupkg
  when: manual
  only:
    - tags
  needs: [ "test" ]
  dependencies:
    - test


deploy_to_swarm:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker stack deploy --with-registry-auth -c docker-compose.yml $STACK_NAME
  only:
    - main
  needs: [ "create_docker_image" ]
  dependencies:
    - create_docker_image
  environment:
    name: production
    url: https://robot.botbot.fr

